# Generated by Django 5.1.6 on 2025-02-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbtelog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='category',
        ),
        migrations.RemoveField(
            model_name='document',
            name='downloads_count',
        ),
    ]
