# Generated by Django 5.1.6 on 2025-06-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbtelog', '0003_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Information'), ('accreditation', 'Accreditation'), ('programs', 'Programs'), ('institutions', 'Institutions'), ('admission', 'Admission'), ('contact', 'Contact Information')], max_length=50)),
                ('keywords', models.TextField(help_text='Comma-separated keywords for matching')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'question'],
            },
        ),
    ]
